# Generated by Django 3.2.1 on 2021-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_recommendation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time_length',
            field=models.CharField(max_length=50),
        ),
    ]
